user:
  name:
    max_length: 50
  email:
    max_length: 255
  pass:
    min_length: 6
  index:
   per_page: 10
author:
  index:
    per_page: 10
publisher:
  per_page: 10
book:
  index:
    per_page: 10
  cols: 60
  rows: 20
